/** Firestore collection name constants — single source of truth */
export const Collections = {
  USERS: "users",
  SUBJECTS: "subjects",
  CLASSROOMS: "classrooms",
  CLASSROOM_AGENDAS: "classroomAgendas",
  AGENDAS: "agendas",
  NOTES: "notes",
  RESOURCES: "resources",
  MEETINGS: "meetings",
  CANVAS_SESSIONS: "canvasSessions",
  MEDIA: "media",
  QUIZZES: "quizzes",
  QUIZ_SESSIONS: "quizSessions",
  QUIZ_RESPONSES: "quizResponses",
  ASSESSMENTS: "assessments",
  ASSESSMENT_QUESTIONS: "assessmentQuestions",
  ASSESSMENT_SUBMISSIONS: "assessmentSubmissions",
  ATTENDANCE_EVENTS: "attendanceEvents",
  BREAKOUTS: "breakouts",
  CHATS: "chats",
  INSIGHTS: "insights",
  SUMMARIES: "summaries",
  MEETING_SLIDES: "meetingSlides",
  CLASS_QUESTIONS: "classQuestions",
  PAYMENTS: "payments",
  PROCESSED_STRIPE_EVENTS: "processedStripeEvents",
  AI_INTERACTIONS: "aiInteractions",
  BRAIN_TOKENS: "brainTokens",
  TOKEN_TRANSACTIONS: "tokenTransactions",
  OFFERS: "offers",
  OFFER_REDEMPTIONS: "offerRedemptions",
  SUPPORT_TICKETS: "supportTickets",
  STUDENT_NOTES: "studentNotes",
  REACTIONS: "reactions",
  REJOIN_REQUESTS: "rejoinRequests",
} as const;
